#!/bin/bash
# EM-Team Quick Completions
# Works with both bash and zsh

# Show all commands when user types /
_em_show_all_commands() {
    echo "🎯 EM-Team Commands (65+ commands available):"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📚 SKILLS (25 commands) - No prefix needed"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  /brainstorming          Explore ideas into designs"
    echo "  /spec-driven-dev        Create specifications before coding"
    echo "  /systematic-debugging   Debug using scientific method"
    echo "  /context-engineering    Optimize agent context"
    echo "  /writing-plans          Write implementation plans"
    echo "  /test-driven-dev        TDD RED-GREEN-REFACTOR"
    echo "  /frontend-patterns      React/Next.js/Vue patterns"
    echo "  /backend-patterns       API/Database patterns"
    echo "  /security-hardening     OWASP Top 10 security"
    echo "  /incremental-impl       Vertical slice development"
    echo "  /subagent-dev           Fresh context per task"
    echo "  /source-driven-dev      Code from official docs"
    echo "  /api-interface-design   Contract-first APIs"
    echo "  /code-review            5-axis code review"
    echo "  /code-simplification    Reduce complexity"
    echo "  /browser-testing        DevTools MCP"
    echo "  /performance-optimization Measure-first optimization"
    echo "  /e2e-testing            Playwright testing"
    echo "  /security-audit         Vulnerability assessment"
    echo "  /api-testing            Integration testing"
    echo "  /git-workflow           Atomic commits"
    echo "  /ci-cd-automation       Feature flags"
    echo "  /documentation          ADRs & docs"
    echo "  /finishing-branch       Merge/PR decisions"
    echo "  /deprecation-migration  Code-as-liability"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🤖 AGENTS (22 commands) - With em- prefix"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  /em-planner               Create implementation plans"
    echo "  /em-executor              Execute plans with atomic commits"
    echo "  /em-code-reviewer         5-axis code review"
    echo "  /em-debugger              Systematic debugging"
    echo "  /em-test-engineer         Test strategy & generation"
    echo "  /em-security-auditor      OWASP security audit"
    echo "  /em-ui-auditor            Visual QA and design review"
    echo "  /em-verifier              Post-execution verification"
    echo "  /em-architect             Architecture & technical design"
    echo "  /em-backend-expert        Database, API, performance"
    echo "  /em-frontend-expert       React/Next.js, UI/UX, performance"
    echo "  /em-database-expert       Schema, queries, fintech patterns"
    echo "  /em-product-manager       Requirements, GAP analysis"
    echo "  /em-senior-code-reviewer  9-axis deep code review"
    echo "  /em-security-reviewer     OWASP + STRIDE security"
    echo "  /em-staff-engineer        Root cause analysis"
    echo "  /em-team-lead             Team coordination"
    echo "  /em-techlead-orchestrator Distributed investigation"
    echo "  /em-researcher            Technical exploration and research"
    echo "  /em-codebase-mapper       Architecture analysis"
    echo "  /em-integration-checker   Cross-phase validation"
    echo "  /em-performance-auditor   Benchmarking and optimization"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔄 WORKFLOWS (18 commands) - With em- prefix"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  /em-new-feature           Idea → Production"
    echo "  /em-bug-fix               Investigate and fix bugs"
    echo "  /em-refactoring           Improve code quality"
    echo "  /em-security-audit        Security assessment"
    echo "  /em-project-setup         Initialize projects"
    echo "  /em-documentation         Generate docs"
    echo "  /em-deployment            Deploy and monitor"
    echo "  /em-retro                 Learn and improve"
    echo "  /em-team-review           Full team review"
    echo "  /em-architecture-review   Architecture review"
    echo "  /em-design-review         UI/UX review"
    echo "  /em-code-review-9axis     Deep 9-axis review"
    echo "  /em-database-review       Database review"
    echo "  /em-product-review        Product review"
    echo "  /em-security-review-advanced Advanced security"
    echo "  /em-incident-response     Production incidents"
    echo "  /em-distributed-investigation  Parallel investigation"
    echo "  /em-distributed-development    Parallel development"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "💬 USAGE EXAMPLES"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  /brainstorming User authentication with JWT"
    echo "  /em-planner Create implementation plan for shopping cart"
    echo "  /em-backend-expert Review API performance"
    echo "  /em-frontend-expert Review React components"
    echo "  /em-database-expert Optimize database queries"
    echo "  /em-code-reviewer Review PR #123"
    echo "  /em-debugger Investigate login timeout bug"
    echo "  /em-security-auditor Audit payment system"
    echo "  /em-new-feature Implement user profile feature"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# Create alias
alias '/'='_em_show_all_commands'
alias 'em-commands'='_em_show_all_commands'
alias 'em-show'='_em_show_all_commands'

# Make the function available for completion
typeset -f _em_show_all_commands > /dev/null

echo "✅ EM-Team completions loaded!"
echo "   Type '/' to see all 65+ commands"
